version: '3.3'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: etcd
    ports:
      - "2379:2379"
      - "2380:2380"
    restart: always
    privileged: true
    command:
      - /usr/local/bin/etcd
      - --config-file=./etcd-conf/etcd0.yaml
    volumes:
      - ./etcd-data:/etcd-data
      - ./etcd-logs:/etcd-logs
      - ./etcd-conf:/etcd-conf

