version: '3.3'

services:
  mountebank:
    image: bbyars/mountebank:2.9.1
    container_name: mountebank
    ports:
      - 2525:2525
      - 4545:4545
      - 5555:5555
      - 11000-11009:11000-11009
    restart: always
    privileged: true

