version: '3.3'

services:
  consul0:
    image: hashicorp/consul:1.11.2
    container_name: consul0
    command: agent -server -bind=0.0.0.0 -bootstrap-expect=3 -client=0.0.0.0
    restart: always
    privileged: true
    volumes:
      - ./node0/consul-data:/consul/data

  consul1:
    image: hashicorp/consul:1.11.2
    container_name: consul1
    command: agent -server -bind=0.0.0.0 -join=consul0 -client=0.0.0.0
    restart: always
    privileged: true
    volumes:
      - ./node1/consul-data:/consul/data
    depends_on:
      - consul0

  consul2:
    image: hashicorp/consul:1.11.2
    container_name: consul2
    command: agent -server -bind=0.0.0.0 -join=consul0 -client=0.0.0.0
    restart: always
    privileged: true
    volumes:
      - ./node2/consul-data:/consul/data
    depends_on:
      - consul0

  consul-client:
    image: hashicorp/consul:1.11.2
    container_name: consul-client
    command: agent -bind=0.0.0.0 -join=consul0 -client=0.0.0.0 -ui
    restart: always
    privileged: true
    ports:
      - "8500:8500"
      - "8600:8600/udp"
      - "8600:8600/tcp"
    volumes:
      - ./node3/consul-data:/consul/data
    depends_on:
      - consul1
      - consul2
