version: '3.3'

services:
  consul0:
    image: hashicorp/consul:1.11.2
    container_name: consul0
    command: agent -server -bootstrap-expect=3
    restart: always
    privileged: true
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    volumes:
      - ./node0/consul-data:/consul/data
      - ./node0/consul-conf/server.json:/consul/config/server.json:ro

  consul1:
    image: hashicorp/consul:1.11.2
    container_name: consul1
    command: agent
    restart: always
    privileged: true
    volumes:
      - ./node1/consul-data:/consul/data
      - ./node1/consul-conf/server.json:/consul/config/server.json:ro

  consul2:
    image: hashicorp/consul:1.11.2
    container_name: consul2
    command: agent
    restart: always
    privileged: true
    volumes:
      - ./node2/consul-data:/consul/data
      - ./node2/consul-conf/server.json:/consul/config/server.json:ro

  consul3:
    image: hashicorp/consul:1.11.2
    container_name: consul3
    command: agent
    restart: always
    privileged: true
    volumes:
      - ./node3/consul-data:/consul/data
      - ./node3/consul-conf/client.json:/consul/config/client.json:ro
