version: '3.3'

services:
  consul0:
    image: consul:1.15.4
    container_name: consul0
    command: "agent -server -bind=0.0.0.0 -bootstrap-expect=3 -ui -client=0.0.0.0"
    restart: always
    privileged: true
    ports:
      - "8500:8500"
    volumes:
      - ./node0/consul-data:/consul/data

  consul1:
    image: consul:1.15.4
    container_name: consul1
    command: "agent -server -bind=0.0.0.0 -join=consul0 -client=0.0.0.0"
    restart: always
    privileged: true
    volumes:
      - ./node1/consul-data:/consul/data
    depends_on:
      - consul0

  consul2:
    image: consul:1.15.4
    container_name: "consul2"
    command: "agent -server -bind=0.0.0.0 -join=consul0 -client=0.0.0.0"
    restart: always
    privileged: true
    volumes:
      - ./node2/consul-data:/consul/data
    depends_on:
      - consul0

  consul3:
    image: consul:1.15.4
    container_name: "consul3"
    command: "agent -bind=0.0.0.0 -join=consul0 -client=0.0.0.0"
    restart: always
    privileged: true
    volumes:
      - ./node3/consul-data:/consul/data
    depends_on:
      - consul0
