version: '3.3'

networks:
  rocketmq:
    driver: bridge

services:
  rocketmqnamesrv:
    image: rocketmqinc/rocketmq
    container_name: rocketmq_namesrv
    ports:
      - "9876:9876"
    restart: always
    environment:
      JAVA_OPT_EXT: "-server -Xms512m -Xmx512m"
    volumes:
      - ./logs:/root/logs
    networks:
      rocketmq:
        aliases:
          - rocketmqnamesrv
    command: sh mqnamesrv

  rocketmqbroker:
    image: rocketmqinc/rocketmq
    container_name: rocketmq_broker
    ports:
      - "10911:10911"
      - "10909:10909"
    restart: always
    environment:
      NAMESRV_ADDR: "rocketmqnamesrv:9876"
      JAVA_OPT_EXT: "-server -Xms512m -Xmx512m -Xmn512m"
    volumes:
      - ./logs:/root/logs
      - ./store:/root/store
      - ./conf/broker.conf:/opt/rocketmq/conf/broker.conf
    networks:
      rocketmq:
        aliases:
          - rocketmqbroker
    depends_on:
      - rocketmqnamesrv
    command: sh mqbroker -c /opt/rocketmq/conf/broker.conf

  rocketmqconsole:
    image: styletang/rocketmq-console-ng
    container_name: rocketmq_console
    ports:
      - 9877:8080
    restart: always
    environment:
      JAVA_OPT: "-Drocketmq.namesrv.addr=rocketmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    volumes:
#      - /etc/localtime:/etc/localtime:ro
      - ./logs/console:/root/logs
    networks:
      rocketmq:
        aliases:
          - rocketmqconsole
    depends_on:
      - rocketmqnamesrv

