version: '3.3'

services:
  filebeat:
    image: elastic/filebeat:7.17.17
    container_name: filebeat
    restart: always
    privileged: true
    user: root
#    networks:
#      - log
#    depends_on:
#      - elasticsearch
#      - logstash
#      - kibana
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./data:/usr/share/filebeat/data
      - /root/nginx/log:/src/logs/nginx
    command: [ "-e", "--strict.perms=false" ]
