version: "3.8"
services:
  db:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    restart: always
    privileged: true
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    command: --default-authentication-plugin=mysql_native_password