version: "3.3"
services:
  db:
    image: mysql
    container_name: mysql_master
    ports:
      - 3306:3306
    restart: always
    privileged: true
    volumes:
      - /root/mysql/data:/var/lib/mysql
      - /root/mysql/logs:/logs
      - /root/mysql/config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
