# 全局配置
global:
  scrape_interval:     15s # 将搜刮间隔设置为每15秒一次。默认是每1分钟一次。
  evaluation_interval: 15s # 每15秒评估一次规则。默认是每1分钟一次。

# Alertmanager 配置
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# 报警(触发器)配置
rule_files:
  - "alert.yml"

# 搜刮配置
scrape_configs:
  # 监控自己
  - job_name: 'prometheus'
    # 覆盖全局默认值，每15秒从该作业中刮取一次目标
    scrape_interval: 15s
    static_configs:
      - targets: ['172.16.96.97:9090']
  # 监控报警
  - job_name: 'alertmanager'
    scrape_interval: 15s
    static_configs:
      - targets: ['alertmanager:9093']
  # 监控docker
  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          instance: Prometheus服务器
  # 监控linux
  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          instance: Prometheus服务器
      - targets: ['172.16.96.98:9100']
        labels:
          instance: 微服务服务器
  # 监控nginx
  - job_name: 'nginx-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['172.16.96.97:9113'] # 不在一个docker-compose network则使用ip地址
        labels:
          instance: Prometheus服务器Nginx
  # 监控go-maxms 动态port
  - job_name: 'go-maxms'
    scrape_interval: 15s
    consul_sd_configs:
      - server: '172.16.96.97:8500'
        services:
          - 'go-maxms'
#    relabel_configs:
#      - source_labels: [ __address__ ]
#        target_label: __param_target
#        action: replace
#        regex: '.*'
#        replacement: '${1}'
  # 监控maxblog
  - job_name: 'maxblog-sgw'
    scrape_interval: 15s
    consul_sd_configs:
      - server: '172.16.96.97:8500'
        services:
          - 'maxblog-sgw'
  - job_name: 'maxblog-user'
    scrape_interval: 15s
    consul_sd_configs:
      - server: '172.16.96.97:8500'
        services:
          - 'maxblog-user'
  - job_name: 'maxblog-main'
    scrape_interval: 15s
    consul_sd_configs:
      - server: '172.16.96.97:8500'
        services:
          - 'maxblog-main'
  - job_name: 'maxblog-stats'
    scrape_interval: 15s
    consul_sd_configs:
      - server: '172.16.96.97:8500'
        services:
          - 'maxblog-stats'
  - job_name: 'maxblog-main-fe'
    scrape_interval: 15s
    consul_sd_configs:
      - server: '172.16.96.97:8500'
        services:
          - 'maxblog-main-fe'
  - job_name: 'maxblog-admin-fe'
    scrape_interval: 15s
    consul_sd_configs:
      - server: '172.16.96.97:8500'
        services:
          - 'maxblog-admin-fe'
