version: "3.8"
services:
  vault-server:
    image: hashicorp/vault
    container_name: vault
    ports:
      - 8200:8200
    restart: always
    privileged: true
    volumes:
      - ./logs:/vault/logs
      - ./file:/vault/file
      - ./config:/vault/config
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_TOKEN: hvs.QIjxtdCfDMwi2APVTwvWR9gN
      VAULT_DEV_ROOT_TOKEN_ID: root
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json