server.host: "0.0.0.0"
server.shutdownTimeout: "5s"
server.publicBaseUrl: "https://kibana.liuzhaomax.cn"
elasticsearch.hosts: [ "http://172.16.96.98:9200" ]
monitoring.ui.container.elasticsearch.enabled: true
